### ISSUE TITLE
Procfile suggestions

### ISSUE THREAD

**Issue by Balaiseee** [bzg/subscribe#14]
The commands `lein run` and  `clojure -M:run` work well to run the application.

Little Procfile suggestions :

- `web: lein run`, Leiningen required
- `web: clojure -M:run`

**Comment by bzg** [comment]
Thanks! I've fixed this now by using `web: lein run`.

The other option is useful too, but the priority is to address the deployment problem on platforms like `dokku` or `scalingo`.
